name: "Test"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    container: 'node:14-alpine'
    steps:
    - uses: actions/checkout@v2
    - name: npm ci
      run: npm ci
    - name: npm test
      run: npm test